name: build_all

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{matrix.os}}

    steps:   
    - name: Chechout repo
      uses: actions/checkout@v4.2.2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.1
      with:
        global-json-file: src/global.json
        cache: true
        cache-dependency-path: |
          **/*.csproj
          **/Directory.Packages.props
          **/Directory.Build.props
          **/Directory.Build.targets
          **/NuGet.config
      
    - name: Run build
      run: pwsh ./build_scripts/build_all.ps1

    - name: Run test
      run: pwsh ./build_scripts/run_tests.ps1 -NoBuild