name: build_all

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  DOTNET_VERSION: 9.0.x

jobs:
  build:
    name: Build ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{matrix.os}}

    steps:   
    - name: Setup .NET
      uses: ./.github/actions/setup-dotnet

    - name: Chechout repo
      uses: ./.github/actions/checkout
      
    - name: Run build_all
      run: pwsh ./build_scripts/build_all.ps1
