name: build_all

on: [push, pull_request, workflow_dispatch]

env:
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}
    - name: Run build_all
      run: pwsh ./build_scripts/build_all.ps1
